apiVersion: apps/v2
kind: Deployment
metadata:
  name: gra-deployment
  labels:
    app: gra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gra
  template:
    metadata:
      labels:
        app: gra
    spec:
      containers:
      - name: gra-deployment
        image: d4wid3k/tetris
        ports:
         - containerPort: 9090
